### DISCUSSION TITLE
Make it easy to choose Snowflake virtual warehouse dynamically

### DISCUSSION THREAD

**Discussion by kanomaxb** [dbt-labs/dbt-snowflake#329] [Ideas]
I would love to be able to tell my script which virtual warehouse it should use depending on whether it is a run, a run with full-refresh or tests. I know there are macros like snowflake_utils.warehouse_size(), but they have some problems: difficult configuration, not working for tests, running chosen warehouse after activating the one from profile thus having 2 warehouses running simultaneously which cause loosing money instead of actually saving.

I'd like it to be a simple config in profiles, sth like:
```
warehouses:
  run: SMALLEST_WH
  full-refresh: LARGE_WH
  tests: MEDIUM_WH
 ```
Do you think it's suitable for a feature request?
