### ISSUE TITLE
[Bug] `not_null` constraint only has effect when specified at the column level 

### ISSUE THREAD

**Issue by matt-winkler** [dbt-labs/dbt-snowflake#1066]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When applying [constraints](https://docs.getdbt.com/reference/resource-properties/constraints) to a [contracted](https://docs.getdbt.com/reference/resource-configs/contract) model, the `not_null` constraint appears to not be evaluated, UNLESS it's applied at the column level. 

Reproduction case:
```
-- in models/test_constraints_application.sql
{{
  config(
    materialized = 'table'
    )
}}

select 1 as id, 'foo' as bar union all
select 1 as id, 'foo' as bar union all
select 1 as id, null as bar
```

```
# schema.yml
models:
  - name: test_constraints_application
    config:
      contract:
        enforced: true
    constraints:
      - type: unique
        columns: [id]
      - type: not_null # has no effect
        columns: [bar]
    columns:
      - name: id
        data_type: int
      - name: bar
        data_type: varchar(3)
        constraints:
          - type: not_null # works as expected
```

### Expected Behavior

I expected the constraint to apply in both of the cases commented in the .yml above. I tried to reproduce this using Databricks, but was unable to do so (i.e. it works as expected in both cases). So it appears this problem may be specific to dbt-snowflake.

### Steps To Reproduce

1. Use version 1.8 of dbt
2. Copy the examples from the Current Behavior section to your project
3. Comment / uncomment the model - level and column - level contraints
4. `dbt run -s test_contraints_application`

### Environment

```markdown
- OS: dbt Cloud 
- Python: dbt Cloud
- dbt-core: dbt Cloud snowflake adapter keep on latest version
- dbt-snowflake: dbt Cloud snowflake adapter keep on latest version
```
