### ISSUE TITLE
DUO MFA authentication doesn't work with Snowflake version 8.24+

### ISSUE THREAD

**Issue by nikzavada** [dbt-labs/dbt-snowflake#1131]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In the current version of dbt-snowflake the next additional parameter has been used to support caching of the token 
`result["client_request_mfa_token"] = True`

### Expected Behavior

I believe based on this documentation https://docs.snowflake.com/en/user-guide/security-mfa#label-mfa-token-caching
the new parameter 
`result["authenticator"] = "username_password_mfa"`
is required to support the expected caching behavior.

### Steps To Reproduce

Every dbt build command requires a DUO approval with Snowflake 8.26

### Environment

```markdown
- OS: Macos
- Python:
- dbt-core: 1.7.11
- dbt-snowflake: 1.7.3
```

**Comment by amychen1776** [comment]
Thank you for opening this - we will look into it and discuss it with Snowflake to confirm the change here.

**Comment by amychen1776** [comment]
@nikzavada I'm curious when you might have seen this behavior change? Did you have MFA enabled already and working with dbt? It appears this has been implemented a while ago at Snowflake so trying to better understand what the change might have been.

**Comment by nikzavada** [comment]
@amychen1776 we just enabled the MFA and I was trying to set it up in dbt to not to approve every run but it didn't work and I spent some time looking around and eventually I came here with my assumption about it :)

**Comment by amychen1776** [comment]
@nikzavada That's helpful to note! I wonder if it could be related to this [issue](https://github.com/dbt-labs/dbt-snowflake/issues/198) where it's not caching the connection. Would you be able to provide a cleaned up version of your profiles.yml (with no sensitive information)?

**Comment by nikzavada** [comment]
@amychen1776 not sure if that can be related. This is a shortened profiles.yml that currently in use

```
config:
  send_anonymous_usage_stats: False

dwh:
  outputs:
    dev_xs:
      type: snowflake
      account: xxxxxxxx.us-east-1
      user: "{{ env_var('PERSONAL_SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('PERSONAL_SNOWFLAKE_PASSWORD') }}"
      authenticator: username_password_mfa
      database: DWH_DEV
      schema: "DBT_{{ env_var('PERSONAL_SNOWFLAKE_USERNAME') }}"
      role: ANALYTICS_ENGINEER
      warehouse: DBT_DEV_WH_XS
      threads: 4
    prod_m:
      type: snowflake
      account: xxxxxxxx.us-east-1
      user: DBT
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      database: DWH
      schema: CORE
      role: DBT_AUTOMATION
      warehouse: DBT_WH_M
      threads: 16
  target: dev_xs
```
