### ISSUE TITLE
[CT-852] [CT-836] [Bug] externalbrowser authenticator opens a browser tab for each dbt thread

### ISSUE THREAD

**Issue by Tolsto** [dbt-labs/dbt-snowflake#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running dbt with Snowflake and `authenticator: externalbrowser` will open a browser login tab for each dbt thread.

### Expected Behavior

Only a single browser window/tab should open regardless how many threads are configured.

### Steps To Reproduce

Execute `dbt run` with the following config (assuming you have at least 4 models to utilize all threads)

```
org:
  outputs:
    dev:
      [...]
      authenticator: externalbrowser
      threads: 4
      type: snowflake
```

### Environment

```markdown
- OS: MacOS 12.4 (arm64)
- Python: 3.9.13
- dbt: 1.1.0 (snowflake plugin 1.1.0)
```

### What database are you using dbt with?

snowflake
