### ISSUE TITLE
[CT-1200] [Bug] Grants colliding with Snowflake Shares

### ISSUE THREAD

**Issue by aaron-ortega** [dbt-labs/dbt-snowflake#264]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt is attempting to revoke `select` permissions on a [Snowflake Share](https://docs.snowflake.com/en/user-guide/data-sharing-intro.html).

### Expected Behavior

dbt's grant feature, release in v1.2, should only apply to roles and not Snowflake shares

### Steps To Reproduce

1. Follows [steps](https://docs.snowflake.com/en/user-guide/data-sharing-provider.html#step-1-create-the-empty-share) 1-3 to
    - create a share
    - grant permissions to the share
    - link a share with a reader account (see [here](https://docs.snowflake.com/en/user-guide/data-sharing-reader-create.html#creating-and-managing-reader-accounts-using-sql) on how to create a reader if one is needed)
2. Add select grant permissions on model tied to share
	  ```sql
	  {{ config(grants = {'select': ['user_c']}) }}
	  ```
3. Run model and error should appear

### Environment

```markdown
- OS: macOS Monterey Version 12.5.1
- Python: 3.9.13
- dbt-core: 1.2.0
- dbt-snowflake: 1.2.0
```

### Additional Context

```sql
-- table with Snowflake share
show grants on table analytics.demand.fridge_hour;
```
![Screen Shot 2022-09-16 at 11 57 14 AM](https://user-images.githubusercontent.com/36523593/190702670-b191c46c-f3e2-4bd6-b408-1f509d631399.png)

![Screen Shot 2022-09-16 at 11 58 44 AM](https://user-images.githubusercontent.com/36523593/190702872-ebb4ac62-3e69-4dfe-ae68-0a25c6d8cffb.png)

**Comment by jtcohen6** [comment]
@aaron-ortega Thanks for opening! Very glad you're using the (relatively new) `grants` feature :)

It sounds like we need an additional bit of logic in our post-processing step, which operates on the result of `show grants`. Similar to what we have currently for `privilege != "OWNERSHIP"`:

https://github.com/dbt-labs/dbt-snowflake/blob/6748104c669d484200e559fe67ae946b2d4e4e65/dbt/adapters/snowflake/impl.py#L160-L172

Something like:
```
granted_to = row["granted_to"]
if granted_to == 'role':  # or != 'share' ?
    ...
```

Would you be interested in contributing the fix? Otherwise someone can pick it up

**Comment by aaron-ortega** [comment]
so fast! i was about to link to the exact code block 

Yes, I would be interested. What behavior should we be thinking about implementing?

1. Skip shares (easy) - we only care about providing permissions for roles

    ```python
    for row in grants_table:
        grantee = row["grantee_name"]
        granted_to = row["granted_to"]
        privilege = row["privilege"]
        if privilege != "OWNERSHIP" and granted_to == "ROLE":
    ```
2. Include shares in granting select. This would require the revoke/grant step to update
    ```sql
    -- e.g.
    revoke SELECT on "table" from "share_name"; --old
    revoke SELECT on "table" from share "share_name"; --new
    ```

**Comment by jtcohen6** [comment]
@aaron-ortega Ooh, that's a good question!

So the quickest way to resolve this bug is probably to remove shares from consideration. Then we could open a feature request about adding support for granting to shares. Might we want dbt to natively support defining/creating/updating shares, too?

If we wanted to support shares, we'd need some way to identify them as such, so that dbt knows to run:
```sql
grant select on <table> to share <share_name>;
grant revoke on <table> from share <share_name>;
```
Instead of:
```sql
grant select on <table> to <share_name>;
grant revoke on <table> from <share_name>;
```

Potential syntaxes:
```yml
models:
  - name: my_model
    config:
      grants:
        # option A: allow strings for default types, or dicts to provide custom type
        select:
          - some_role
          - name: some_share
            type: share
        # option B: inspired by google/bigquery, use string prefixes for principal type
        select:
          - some_role  # could also be role:some_role
          - share:some_share
```
