### ISSUE TITLE
[CT-1281] [Bug] column names are not escaped in tests even if quoted in schema.yml

### ISSUE THREAD

**Issue by sta-ck** [dbt-labs/dbt-snowflake#284]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Similar to https://github.com/dbt-msft/dbt-sqlserver/issues/121 - I wrote a test with a column with a space in its name "Has logged in in the last 30 days", and tested it for not_null, the generated test does not quote the name of the column and fails in Snowflake. 

I tried to change the yml name to be double (and eventually single) quoted and ran it again with the same behavior. 

### Expected Behavior

I would expect the column name to be double quoted in snowflake to allow arbitrary identifiers. 

### Steps To Reproduce

1. Create a model (I used a view but it probably doesn't matter) and create a new column with a space in its name. ``` select null as "this column has a space in its name"```
3. Test the column is not_null in your schema.yml
4. The test fails as it writes out the test like the following:
```
select this column has a space in its name
from database.schema.☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺
where this column has a space in its name is null
```

### Relevant log output

```shell
Actual error from a relevant log 


[0m22:47:14.961278 [debug] [Thread-1  ]: Database Error in test not_null_* (models\stack_overflow\schema.yml)
  001003 (42000): SQL compilation error:
  syntax error line 12 at position 17 unexpected '1'.
  syntax error line 14 at position 10 unexpected 'asked'.
  compiled SQL at target\run\core_metrics\models\stack_overflow\schema.yml\not_null_*_15a5ebc1410cad026adc07cb5988bff7.sql
```

### Environment

```markdown
- OS: Windows 10 Enterprise 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)
- Python: Python 3.8.10
- dbt-core: 1.2.1
- dbt-snowflake: 1.2.0
```

**Comment by sta-ck** [comment]
So after finding https://docs.getdbt.com/reference/resource-properties/quote I am closing this as I have a workaround but it still seems weird that identifier doesn't quote identifiers when running these tests.

**Comment by jtcohen6** [comment]
@sta-ck Just to clarify — you were able to get this working when you set:
```yml
version: 2
models:
  - name: model_name
    columns:
      - name: 'Has logged in in the last 30 days'
        quote: true
        tests:
          - not_null
```
But it was not working when you added the quotes within the yaml (including the awkward double-quoting shown below)?
```yml
version: 2
models:
  - name: model_name
    columns:
      - name: '"Has logged in in the last 30 days"'
        tests:
          - not_null
```
