### ISSUE TITLE
[CT-2138] Support to OAUTH snowflake connection for dbt-core

### ISSUE THREAD

**Issue by gsugumar** [dbt-labs/dbt-snowflake#474]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

support OAUTH snowflake connection for dbt-core

**Comment by dbeatty10** [comment]
Thanks for reaching out @gsugumar !

You're in luck -- we already have support for OAuth connections in dbt-snowflake (implemented in https://github.com/dbt-labs/dbt-core/pull/2069)!

However, you might find that one of the methods listed [here](https://docs.getdbt.com/reference/warehouse-setups/snowflake-setup) is easier to set up and use.

It's a bit complex to set up all the pieces, but here's the relevant portion of your `profiles.yml` to use OAuth:
```yaml
my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <ACCOUNT_ID>

      # Here's the specific pieces to configure OAuth 
      authenticator: oauth
      oauth_client_id: <OAUTH_CLIENT_ID>
      oauth_client_secret: <OAUTH_CLIENT_ID>
      token: <OAUTH_REFRESH_TOKEN>
```

**Note**: `token` is a _refresh_ token rather than an _access_ token.

This method assumes you have followed a guide like [this](https://community.snowflake.com/s/article/HOW-TO-OAUTH-TOKEN-GENERATION-USING-SNOWFLAKE-CUSTOM-OAUTH) to generate a **refresh** token. I also found [this](https://docs.getdbt.com/docs/collaborate/manage-access/set-up-snowflake-oauth) to be useful, especially the [troubleshooting](https://docs.getdbt.com/docs/collaborate/manage-access/set-up-snowflake-oauth#troubleshooting) section.

Closing as a duplicate of https://github.com/dbt-labs/dbt-core/issues/2050.
