### ISSUE TITLE
[ADAP-771] [Regression] Version 1.6.0 fails when running incremental models

### ISSUE THREAD

**Issue by MavenFlint** [dbt-labs/dbt-snowflake#724]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Version 1.6.0 fails when running incremental models.

### Expected Behavior

Incremental models are failing due to unexpected ';' error.

### Steps To Reproduce

1. Run incremental model.
2. Model fails with error.

### Relevant log output

```shell
Failed query:
DROP VIEW <db>.<schema>.<model>__dbt_tmp.;

SQL compilation error: syntax error line 1 at position 52 unexpected ';'.
```

### Environment

```markdown
- OS:ubuntu-20.04 on Azure Hosted Runner
- Python: 3.10
- dbt-core:1.6.0 (installed via pip install dbt-snowflake)
- dbt-snowflake:1.6.0
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @MavenFlint 🙏 

We have [some code in dbt-core](https://github.com/search?q=repo%3Adbt-labs%2Fdbt-core+__dbt_tmp&type=code) that  is related to `__dbt_tmp`, but it surprises me to see a `.` right before the semicolon `;`.

I also didn't expect to see the capitalized `DROP VIEW` statement because dbt-core and dbt-snowflake use lowercasing.

Can you share the model definition that is failing for you? And the associated command?

Something like this would help us try to reproduce the issue you are seeing:

`models/my_model.sql`
```sql
{{ config(materialized="incremental") }}

select 1 as id
```

```shell
dbt run -s my_model
```

**Comment by MavenFlint** [comment]
The error was taken from the query history in Snowflake.

`project_config.yml`
```
name: 'company'
version: '0.1'
profile: 'company'
config-version: 2

analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"


models:
    +transient: "{{ false if target.name == 'prod' else true }}"
    database1:
        company:
            staging:
                +tags: stg_view
                +materialized: view
            enhanced:
                +materialized: table
        +persist_docs:
            columns: true

<seed stuff redacted>
```

`model.sql`

```
{{ 
  config
    (
      schema='enhanced', 
      materialized='incremental',
      unique_key = 'table_sk'
    ) 
}}

<query redacted>
```

`dbt build --select +model+`
