### ISSUE TITLE
Use lowercase / case-insensitive comparison when persisting column-level comments for views

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-snowflake#73]
See https://github.com/dbt-labs/dbt-snowflake/issues/72 for context

https://github.com/dbt-labs/dbt-snowflake/blob/e75986f0b81749bc790f52dcea4ecd1c1a7f3f2a/dbt/include/snowflake/macros/adapters.sql#L47-L50

This check should use `|lower` instead of `|upper`, since Snowflake columns are almost always uppercase.

```python
model_columns:  {'id': {'name': 'id', 'description': 'this is a cool column', 'meta': {}, 'tags': []}}
query_columns:  ['ID']
```

That will enable users to persist descriptions for columns defined in lowercase:
```yml
version: 2

models:
  - name: my_cool_view_model
    description: this is a cool model
    config:
      materialized: view
      persist_docs:
        relation: true
        columns: true
    columns:
      - name: id # instead of ID
        description: this is a cool column
```
