### ISSUE TITLE
[Bug] `copy_grants` option is not valid while using dbt-python in dbt-snowflake

### ISSUE THREAD

**Issue by sora32127** [dbt-labs/dbt-snowflake#905]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Situation : 
- `copy_grants` option is enabled in `dbt_project.yml` 
- manually I granted select previlage for models created by dbt-python to a role. 

Behavior : 
- execute `dbt run --select dbt_python_model` , then the grants that enables select to `dbt_python_model`  was  revoked. 

### Expected Behavior

with copy grant set in dbt_project.yml, the existing grants on the `dbt_python_model` should be remain as it is.

### Steps To Reproduce

1. prepare sample dbt-python model

```python
import pandas as pd

def model(dbt, session):
    dbt.config(packages=["pandas==1.5.1"])

    df = pd.DataFrame(
        {
            "id": [1, 2, 3, 4, 5],
            "name": ["Alice", "Bob", "Charlie", "David", "Eve"],
            "age": [24, 19, 34, 23, 31],
        }
    )
    return df
```

put this python file under directory : my_project/mst

and prepare `dbt_project.yml` file :

```yml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2

profile: "my_dbt_project"
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:
  - "target"
  - "dbt_packages"
models:
  snowflake_warehouse: "DBT_WH"
  my_dbt_project:
    dbt-osmosis: "{model}.yml"
    copy_grants: true
    mst:
      materialized: table
```

2. execute model : 
```shell
dbt run --select dbt_python_model
```

3. mannually grant in Snowsight:

```sql
use role accountadmin;

create role if not exists github_raise_issue_role;
grant role github_raise_issue_role to role accountadmin;

grant select on table my_db.public.dbt_python_model to role github_raise_issue_role;
grant usage on database my_db to role github_raise_issue_role;
grant usage on schema my_db.public to role github_raise_issue_role;
grant usage on warehouse compute_wh to role github_raise_issue_role;

show grants to role github_raise_issue_role;
```

Some grants will show. These grants include select permission on the table "dbt_python_model".

4. rerun model : 

```shell
dbt run --select dbt_python_model
```

5. show grants:

```sql
show grants to role github_raise_issue_role;
```

Then confirm that select permission to table "dbt_python_model" will not show

### Environment

```markdown
- OS: MacOS Sonoma 14.1.1
- Python:3.9.0
- dbt-core:1.7.4
- dbt-snowflake:1.7.1
```
