### ISSUE TITLE
[Bug] dbt seed --full-refresh sql compilation error

### ISSUE THREAD

**Issue by bhagyasharma** [dbt-labs/dbt-snowflake#911]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I recently upgraded my `dbt-snowflake` from 1.4.0 -> 1.7.1 (also upgrading dbt-core) and noticed a failure when trying to run `dbt seed --full-refresh`
when looking into the query that runs in snowflake it generates the drop table statement as:
`DROP TABLE IF EXISTS <DATABASE>.<SCHEMA>.<SEED_TABLE> .`
The added period at the end of the statement is causing the error. 
This is the dbt error
```
20:11:41    Database Error in seed dim_seed_table (seeds/dim_seed_table.csv)
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 94 unexpected '<EOF>'.
```

### Expected Behavior

The table should be dropped with a cascade (at least this is what is happening in 1.4.0).

### Steps To Reproduce

1. create a seed table (csv format)
2. Only configs under dbt_project.yml are:
```
seed-paths: ["seeds"]
seeds:
  +tags:
    - "seeds"
```
3. run `dbt seed --full-refresh`

### Environment

```markdown
- OS: Ventura 13.5
- Python: 3.10.10
- dbt-core: 1.7.8
- dbt-snowflake:1.7.1
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @bhagyasharma !

I was not able to replicate this bug report. Could you please try to replicate this again on your end?

If you are able to replicate it, can you share the relevant project files so that we can replicate it as well?

### My attempt to replicate

Here are my project files:

`seeds/dim_seed_table.csv`

```
id
1
```

`dbt_project.yml`

```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "snowflake"

seed-paths: ["seeds"]
seeds:
  +tags:
    - "seeds"
```

I did the following steps:
1. Activated an environment using dbt-core and dbt-snowflake ~=1.4
1. Ran `dbt seed --full-refresh` twice
1. Activated an environment using dbt-core==1.7.8 and dbt-snowflake==1.7.1
1. Ran `dbt seed --full-refresh` twice

And here's my successful command:
```
$ dbt seed --full-refresh

22:42:44  Running with dbt=1.7.8
22:42:46  Registered adapter: snowflake=1.7.1
22:42:46  Found 1 seed, 0 sources, 0 exposures, 0 metrics, 430 macros, 0 groups, 0 semantic models
22:42:46  
22:42:47  Concurrency: 10 threads (target='snowflake')
22:42:47  
22:42:47  1 of 1 START seed file dbt_dbeatty.dim_seed_table .............................. [RUN]
22:42:49  1 of 1 OK loaded seed file dbt_dbeatty.dim_seed_table .......................... [CREATE 1 in 1.98s]
22:42:49  
22:42:49  Finished running 1 seed in 0 hours 0 minutes and 3.64 seconds (3.64s).
22:42:49  
22:42:49  Completed successfully
22:42:49  
22:42:49  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

Here's the statement that I saw in my `logs/dbt.log` file:
```
drop table if exists "ANALYTICS_DEV"."DBT_DBEATTY"."DIM_SEED_TABLE" cascade
```

**Comment by bhagyasharma** [comment]
@dbeatty10 appreciate the quick response! Some more details about the project:
We have 25 seeds running but for simplicity here is a basic one:
seeds/dim_event_type_id
```
EVENT_TYPE_ID,EVENT_TYPE
1,SALE
2,LISTING
3,RENTAL
```

dbt_project.yml
```
name: 'snowflake_real_estate'
version: '1.0.0'
config-version: 2

profile: 'snowflake_real_estate'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - '{{ extract_dict_val() }}'
  - '{{ flatten_keys_list() }}'
  - '{{ merge_dicts() }}'

seeds:
  +tags:
    - "seeds"
```

~/.dbt/profiles.yml
```
config:
  send_anonymous_usage_stats: False
  use_colors: True

snowflake_real_estate:
  target: prod
  outputs:
    prod:
        type: snowflake
        account: "{{ env_var('SNOWFLAKE_PROD_ACCOUNT') }}"
        database: ANALYTICS
        schema: PHYS_REAL_ESTATE
        warehouse: TRANSFORMING_M
        role: TRANSFORMER
        user: "{{ env_var('SNOWFLAKE_DBT_PROD_USERNAME') }}"
        password: "{{ env_var('SNOWFLAKE_DBT_PROD_PASSWORD') }}"
        threads: 4
        client_session_keep_alive: false
```


There is also a dependency of dbt_utils version 1.1.1
packages.yml
```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1

```

I was able to reproduce this, here is a portion of logs/dbt.log
```
[0m09:39:04.186830 [debug] [Thread-1 (]: Began running node seed.snowflake_real_estate.dim_event_type_id
[0m09:39:04.187227 [info ] [Thread-1 (]: 13 of 25 START seed file PHYS_REAL_ESTATE.dim_event_type_id .................... [RUN]
[0m09:39:04.187674 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly seed.snowflake_real_estate.dim_cs_10_to_counties, now seed.snowflake_real_estate.dim_event_type_id)
[0m09:39:04.187915 [debug] [Thread-1 (]: Began compiling node seed.snowflake_real_estate.dim_event_type_id
[0m09:39:04.188185 [debug] [Thread-1 (]: Timing info for seed.snowflake_real_estate.dim_event_type_id (compile): 09:39:04.188064 => 09:39:04.188066
[0m09:39:04.188410 [debug] [Thread-1 (]: Began executing node seed.snowflake_real_estate.dim_event_type_id
[0m09:39:04.193023 [debug] [Thread-1 (]: Applying DROP to: "ANALYTICS"."PHYS_REAL_ESTATE"."DIM_EVENT_TYPE_ID"
[0m09:39:04.193467 [info ] [Thread-1 (]: DROPPING "ANALYTICS"."PHYS_REAL_ESTATE"."DIM_EVENT_TYPE_ID".
[0m09:39:04.193913 [debug] [Thread-1 (]: Using snowflake connection "seed.snowflake_real_estate.dim_event_type_id"
[0m09:39:04.194154 [debug] [Thread-1 (]: On seed.snowflake_real_estate.dim_event_type_id: /* {"app": "dbt", "dbt_version": "1.7.8", "profile_name": "snowflake_real_estate", "target_name": "prod", "node_id": "seed.snowflake_real_estate.dim_event_type_id"} */
DROP TABLE IF EXISTS "ANALYTICS"."PHYS_REAL_ESTATE"."DIM_EVENT_TYPE_ID".
[0m09:39:04.194375 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
```

That should be all relevant files, let me know if I can provide any additional info. My teammate was also able to reproduce this on his local environment so it definitely has to be config related.
